repos:
  - repo: https://github.com/bahjat/pre-commit-golang
    rev: v1.0.0
    hooks:
      - id: go-fmt-import
      # - id: go-vet
      # - id: go-lint
      # - id: go-unit-tests
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.6.2"
    hooks:
      - id: prettier
